### ISSUE TITLE
Get VC1 servers metada endpoint support?

### ISSUE THREAD

**Issue by PedroMD** [scaleway/api.scaleway.com#22]
Hello,

Having a metadata endpoint for C1 servers is great, but can we also have the same for the VC1s' ? Its pretty handy having such an endpoint so we can dynamically assign our flexible IP to the correct machine when designing High Availability at the load balance level with HAProxy and Keepalived's scripts (where we would get each servers' info via this metadata endpoint).

Thanks in advance!

Pedro

**Comment by PedroMD** [comment]
Good to know! Thanks!

**Comment by moul** [comment]
Hi @PedroMD, as you can see in my commit, this method is available for all our server types :)

**Comment by PedroMD** [comment]
Yeah, I got it - thanks! Will deploy my first scaleway server then :)

**Comment by moul** [comment]
perfect, if you have any trouble using the API, do not hesitate to ping us here, I think we still have some minor incoherencies due to recent changes in the API
