### ISSUE TITLE
API -> create server -> how to specify server type? (i.e: C1, C2[SML], VC1S)

### ISSUE THREAD

**Issue by leovin** [scaleway/api.scaleway.com#36]
looks like there is some notion of server type in code https://github.com/scaleway/scaleway-cli/blob/v1.9.0/pkg/api/api.go#L515

could you please provide curl example of creating server with specific type?

**Comment by leovin** [comment]
commercial-type/commercial_type  available in most clients (go, cli, salt), just not documented
at least there's source code to look at :)

**Comment by bchatelard** [comment]
It has been updated on the api documentation, not re-deployed yet.

https://github.com/scaleway/api.scaleway.com/blob/master/contents/server.md#group-servers
