### ISSUE TITLE
terminate an instance

### ISSUE THREAD

**Issue by gunph1ld** [scaleway/api.scaleway.com#38]
Hello!

How to terminate an instance without transferring data? I can't find in the documentation (but it's possible via the web panel)

Thanks

**Comment by QuentinPerez** [comment]
Hi @gunph1ld,

Our console use the API, to show the actions, you can inspect the page and open `Network` onglet
```console
curl 'https://api.scaleway.com/servers/86173547-5e48-4a1a-a18c-c71638224807/action' -H 'Content-Type: application/json' -H 'x-auth-token: 00000000-0000-0000-0000-0000000000' --data-binary '{"action":"terminate"}'
```

**Comment by gunph1ld** [comment]
Thanks! It works.

But I really don't understand, why a guy from support told me, that it's impossible. Seems support in the control panel is incompetent.
