### ISSUE TITLE
no support for user_data in create server API

### ISSUE THREAD

**Issue by komuw** [scaleway/api.scaleway.com#40]
I think it would be great to have ability to send user_data(usually text that is interpreted as bash script) when creating a server via the API, https://github.com/scaleway/api.scaleway.com/blob/master/contents/server.md#create-a-new-server-post 

This way, a scaleway customer can be able to specify things that they would like to run during the server creation. 

This already exists in other cloud platforms, eg:
1. The ovh create server api has a parameter called `userData` that you can specify:: https://api.ovh.com/console/#/cloud/project/%7BserviceName%7D/instance#POST     
2. The digitalocean API also takes a parameter called `user_data`, https://developers.digitalocean.com/documentation/v2/#create-a-new-droplet   

This is very useful especially when you want to automate creation of servers that are different from each other but are based off the same image.

**Comment by vilagithub** [comment]
https://developer.scaleway.com/#user-data with a 'cloud-init' key works.

You also need the cloud-init package installed (scaleway is a data source since ~0.7.9).

**Comment by vipera7** [comment]
@vilagithub Can you please add an exemple of usage ?
I tried :
```
curl https://cp-"$REGION_URL".scaleway.com/servers/"$ID_SERVER"/user_data/cloud-init -H "X-Auth-Token: $TOKEN" -X PUT "Content-Type: text/cloud-config" -d '
package_upgrade: true
runcmd:
- [ wget, "https://wordpress.org/latest.zip", -O, /run/latest.zip ]'
```
But I have this error

> {"message": "The method is not allowed for the requested URL.", "type": "405"}curl: (6) Could not resolve host: Content-Type; Unknown error


I run the command after creating the server. I use the image CentOS 7.4 and START1-S

**Comment by danhunsaker** [comment]
`PUT` != `PATCH`

**Comment by vipera7** [comment]
How did I miss this

But after I corrected it I get an another error :
`Content-Type must be text/plain and not application/x-www-form-urlencodedcurl: (6) Could not resolve host: Content-Type; Unknown error`

The request :
```
 curl https://cp-"$REGION_URL".scaleway.com/servers/"$ID_SERVER"/user_data/cloud-init -H "X-Auth-Token: $TOKEN" --request PATCH "Content-Type: text/plain" -d '
package_upgrade: true
runcmd:
- [ wget, "https://wordpress.org/latest.zip", -O, /run/latest.zip ]'
```

**Comment by danhunsaker** [comment]
So your first revision lost a `-H` before the `ContentType` header, so it wasn't treated as a header. Your second revision lost the `cloud-init` part of the path. If you use your original version, and simply replace `PUT` with `PATCH` (changing nothing else), that should work fine.
