### ISSUE TITLE
swagger.json has errors and can't be imported into swagger editor 

### ISSUE THREAD

**Issue by Vad1mo** [scaleway/api.scaleway.com#44]
I am trying to import the current `swagger.json` into the swagger editor to create a client DSK for Java/Groovy.

Because of those errors its not possible.

![bildschirmfoto 2017-03-05 um 15 35 42](https://cloud.githubusercontent.com/assets/1492007/23588151/72a33412-01b9-11e7-8500-68f5e3ace3c3.png)

How to reproduce
Go to `http://editor.swagger.io/#!/` import the swagger.json file https://raw.githubusercontent.com/scaleway/api.scaleway.com/master/swagger.json

See the result

**Comment by bchatelard** [comment]
Closing, we removed the swagger.json file, the reference documentation is https://developer.scaleway.com/
