### ISSUE TITLE
Fail to attach IP address to new server

### ISSUE THREAD

**Issue by terarows** [scaleway/api.scaleway.com#47]
I make 3 consecutive API calls similar to the following _curl_ commands. The last (third) call gets the error message I can not interpret.

Note that the first call get the response from Scaleway almost immediately. If I remember correctly, last time I manually created a server through control panel, Scaleway did not complete its job within one minute. I therefore suspect that the error produced by the 3rd API call is because Scaleway can not attach IP address to newly created server when it is not truely ready.

1. create server:

        curl -H 'X-Auth-Token: my-token' -H 'Content-Type: application/json' --data '{"organization":"bc7c74ab-7162-4bde-a931-1f9afb070340","name":"25","image":"e14c79ad-5371-4a11-839b-310ff2d1fbc5","commercial_type":"VC1S"}' https://cp-ams1.scaleway.com/servers

    response:

        32eaa8d1-6bfc-440f-972a-aa26b207a7bc

2. create IP:

        curl -H 'X-Auth-Token: my-token' -H 'Content-Type: application/json' --data '{"organization":"bc7c74ab-7162-4bde-a931-1f9afb070340"}' https://cp-ams1.scaleway.com/ips

    response:

    ip address:

        51.15.59.31

    ip id:

        b6a9fc01-288a-4339-8d73-9a02e9d5c783

3. attach IP to server:

        curl -X PUT -H 'X-Auth-Token: my-token' -H 'Content-Type: application/json' --data {"address":"51.15.59.31","id":"b6a9fc01-288a-4339-8d73-9a02e9d5c783","organization":"bc7c74ab-7162-4bde-a931-1f9afb070340","server":"32eaa8d1-6bfc-440f-972a-aa26b207a7bc"}' https://cp-ams1.scaleway.com/ips/b6a9fc01-288a-4339-8d73-9a02e9d5c783

    response:

        {"fields": {"reverse": ["required key not provided"]}, "message": "Validation Error", "type": invalid_request_error"}

**Comment by bchatelard** [comment]
This error means that another key `reverse` is required if you need to update an ip address.
Take a look at the body returned by the API on the ip address creation, you can change the `server` property and send the body back, it should work.

**Comment by terarows** [comment]
Thanks for the reply!

I will test it after this one more question:

How do I know if the new server is ready for me to install software?
Should I repeatedly call https://developer.scaleway.com/#servers-server-get and check whether or not "server.state" is "running"? Are there more intelligent ways?

**Comment by terarows** [comment]
I am now able to attach IP address to server by calling https://developer.scaleway.com/#ips-ip-put with added parameter  _"reverse":null_ in body.

The server state is "stopped" after it is created. Now I want to start the server so that I can install software. Calling https://developer.scaleway.com/#servers-server-put with _"state":"running"_ in body does not start the server. What is the correct way to start stopped servers?

**Comment by tbillon** [comment]
You must use server actions: https://developer.scaleway.com/#servers-actions-post
