### ISSUE TITLE
Not clear how to enable local boot via API

### ISSUE THREAD

**Issue by jackivanov** [scaleway/api.scaleway.com#62]
Hello, 

There is no any documentation in the API docs about how to enable local boot. What to put in the body?

Thanks!

**Comment by jackivanov** [comment]
I've managed to intercept it via developer tools in my browser. The key is `boot_type: local`
Bloody hell, scaleway, fix the documentation at last long! I'm not the only one who facing a docs related issue.

Thanks!

**Comment by sieben** [comment]
Hello,

The documentation at the page: https://github.com/scaleway/api.scaleway.com/blob/master/contents/server.md shows that ```
"boot_type": "local"``` shoud be used in the body of the request going to the compute API.

**Comment by jackivanov** [comment]
It would be sensible to update the documentation on your official site https://developer.scaleway.com/

**Comment by sieben** [comment]
Indeed. We are very sorry about not putting it sooner on the main website.
A fix is on its way.

Le mar. 29 mai 2018 à 16:55, Jack Ivanov <notifications@github.com> a
écrit :
