### ISSUE TITLE
GET /users/:id not returning all the SSH keys

### ISSUE THREAD

**Issue by Ilshidur** [scaleway/api.scaleway.com#67]
Hello.

I'm creating this issue after contacting the support. They've told me to ask here.

I recently started encountering errors when provisioning a SSH key using Terraform with the Scaleway provider :
- When "apply"ing for the 1st time, the SSH key is created (the Scaleway provider uses the route PATCH /users/:id).
- When "apply"ing for the 2nd time, I get the error "ssh key does not exist anymore" (the provider uses the route GET /users/:id).

Turns out the problem is caused by the API.
It looks like the GET /users/:id method does not return all the SSH keys, but the PATCH route does. When inspecting the PATCH call for the key creation, I can observe the full list being returned by the API and shown in the UI.

I managed the reproduce the bug in 2 different ways :
- Using Terraform, here is the configuration : https://gist.github.com/Ilshidur/dac1400c7ef541157ddd8bb146879bd8
- Using cURL : https://gist.github.com/Ilshidur/8163fdf92860cbaf85d0bb9f8e37b3bd (there's my session ID, but it's expired)

I don't get why this is happening.
Thank you.

**Comment by Sweenu** [comment]
Thanks for creating this issue, a potential fix has just been pushed to production.
Could you try again and tell us if the problem persists?

**Comment by Ilshidur** [comment]
Looks like this is fixed ! I'm now able to see my SSH keys in the UI :-)
I also tested via the API. Looks good to me.

Thank you for your quick fix.
