### ISSUE TITLE
How to use the cloud.init on the API ?

### ISSUE THREAD

**Issue by vipera7** [scaleway/api.scaleway.com#68]
I'm having trouble to use correctly the cloud.init throught the API.
I made some try with several commands but always failing.

```
curl -X PUT https://cp-par1.scaleway.com/servers/"$ID"/user_data/ -H "X-Auth-Token: $TOKEN" -H "Content-Type: text/plain" -d '
#cloud-config
package_upgrade: true
runcmd:
- [ wget, "https://wordpress.org/latest.zip", -O, /run/latest.zip ]'
```

> {"message": "The method is not allowed for the requested URL.", "type": "405"}

```
curl --request PATCH -d '#cloud-config
package_upgrade: true' -H 'X-Auth-Token:  $TOKEN' https://cp-par1.scaleway.com/servers/"$ID"/user_data/cloud-init
```

> Content-Type must be text/plain and not application/x-www-form-urlencoded

What I'm doing wrong ?

**Comment by brmzkw** [comment]
`PUT` is not implemented to edit userdata, only `PATCH` is.

As the error message explains, the text/plain content-type header must be set with `-H Content-Type: text/plain`.

Full working example:

```bash
$> cat<<EOF > userdata
#cloud-config
package_upgrade: true
runcmd:
- [ wget, "https://wordpress.org/latest.zip", -O, /run/latest.zip ]'
EOF

$> curl \
    -H 'X-Auth-Token: <TOKEN>' \
    -H 'Content-Type: text/plain' \
    -X PATCH \
    https://cp-par1.scaleway.com/servers/<SERVER ID>/user_data/cloud-init \
    --data-binary '@userdata'
```

**Comment by vincelwt** [comment]
@brmzkw The doc is outdated and says to use PUT https://www.scaleway.com/en/docs/how-to-use-cloud-init-to-configure-your-server-at-first-boot/#-Using-CloudInit-with-Scaleway-API

**Comment by vincelwt** [comment]
@brmzkw The doc is outdated and says to use PUT https://www.scaleway.com/en/docs/how-to-use-cloud-init-to-configure-your-server-at-first-boot/#-Using-CloudInit-with-Scaleway-API
