### ISSUE TITLE
PUT on volumes behaves oddly. Cant omit fields

### ISSUE THREAD

**Issue by arianvp** [scaleway/api.scaleway.com#8]
Say I want to PUT on a volume I must provide the following fields:

```
{
  "fields": {
    "name": [
      "required key not provided"
    ],
    "modification_date": [
      "required key not provided"
    ],
    "export_uri": [
      "required key not provided"
    ],
    "volume_type": [
      "required key not provided"
    ],
    "creation_date": [
      "required key not provided"
    ],
    "server": [
      "required key not provided"
    ],
    "id": [
      "required key not provided"
    ],
    "size": [
      "required key not provided"
    ]
  },
  "message": "Validation Error",
  "type": "invalid_request_error"
}
```

So an example data that will be accepted is:

PUT on  `/volumes/de305d54-75b4-431b-adb2-eb6b9e546014`

```
{
    "organization":"1111111-1111-1111-1111-1111111111",
    "name": "lol",
    "modification_date": "nbladashd",
    "export_uri": null,
    "volume_type": "l_ssd",
    "creation_date": "bogus date. but gets accepted anyway",
    "server": null,
    "id": "de305d54-75b4-431b-adb2-eb6b9e546014",
    "size": 5000000000
}
```

There are a few weird things happening if I omit fields.

I have to specify the `id` field, or otherwise I get an error that `id` is required. Which is weird because `id` is already in the URL.

Also I _need_ to set `modification_date` and `creation_date` but their values are always ignored.

It would be cool to be able to omit fields that I don't want to change.  For example  I want to omit a `name` if I just want to update a `size`.  

Perhaps we'd want to put the behaviour I describe as a `PATCH` ?

**Comment by moul** [comment]
@arianvp, yep, our `PUT` requests needs a whole object, i.e:

* `GET` resource
* edit field(s)
* `PUT` edited-resource

---

Even if `PATCH` is not yet documented (#5), but most of our resources handle `PATCH` requests

As you are writing a wrapper, I suggest you just to give a try and check, in scaleway-cli, we already implemented some PATCH requests (see https://github.com/scaleway/scaleway-cli/blob/079c92660dd317c252fc4d2fca0171a11ecb1429/pkg/cli/x_patch.go), but not yet the volume attach

**Comment by arianvp** [comment]
`volumes` doesn't handle `PATCH` yet I think. I currently get this:
```
{
  "message": "The method is not allowed for the requested URL.",
  "type": "405"
}
```

**Comment by edouardb** [comment]
You're right @arianvp, at the moment volumes support:

`GET`, `PUT`, `POST` and `DELETE`

`PATCH` is not implemented yet.
